-- =============================================================================
-- SAN LUCAS CAFE POS — TAM YEDEKLEME (BOOTSTRAP) DOSYASI
-- =============================================================================
-- Bu dosya, San Lucas backend'ini SIFIRDAN yeni bir (boş) Supabase projesinde
-- yeniden oluşturur. Kaynak proje ref: gscuotgjxmcemmkbajtd (canlı proje,
-- SADECE okuma sorgularıyla incelendi — bu dosya oradan üretildi).
--
-- Bu dosyayı yeni projenin SQL Editor'ünde TEK SEFERDE, en baştan sona kadar
-- çalıştırın. Tekrar çalıştırmak da güvenlidir (idempotent) — tablo/politika/
-- fonksiyon/trigger'lar var olsa bile hata vermez.
--
-- İçindekiler:
--   1. Extensions (eklentiler)
--   2. Tablolar (public şeması, 15 tablo)
--   3. Index'ler (kısıtlardan otomatik oluşmayanlar)
--   4. Fonksiyonlar (7 adet, public şeması)
--   5. Trigger'lar (orders üzerinde 2 + auth.users üzerinde 1)
--   6. Row Level Security + Policy'ler (public: 58, storage: 4)
--   7. Storage bucket'ları
--   8. Realtime publication üyeliği
--   9. Fonksiyon grant/revoke'ları
--   10. Seed data (sadece masalar / tables)
-- =============================================================================


-- =============================================================================
-- 1. EXTENSIONS
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";
CREATE EXTENSION IF NOT EXISTS "supabase_vault";


-- =============================================================================
-- 2. TABLOLAR (bağımlılık sırasına göre)
-- =============================================================================

-- ---- tables (masalar) -------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tables (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  status      text DEFAULT 'empty',
  created_at  timestamp without time zone DEFAULT now()
);

-- ---- categories --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id    text UNIQUE,
  name        text NOT NULL,
  color       text DEFAULT '#e8975a',
  icon        text DEFAULT 'tag',
  image_url   text
);

-- ---- products ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.products (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id      text UNIQUE,
  name          text NOT NULL,
  price         numeric(10,2) NOT NULL,
  stock         integer DEFAULT 0,
  category_id   integer REFERENCES public.categories(id) ON DELETE SET NULL,
  image_url     text,
  recipe        text,
  is_active     boolean DEFAULT true,
  created_at    timestamp with time zone DEFAULT now(),
  points_value  integer NOT NULL DEFAULT 0
);

-- ---- profiles (auth.users'a 1:1 uzanır) --------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id                    uuid PRIMARY KEY REFERENCES auth.users(id),
  full_name             text,
  role                  text DEFAULT 'waiter',
  can_take_orders       boolean DEFAULT true,
  can_close_tables      boolean DEFAULT false,
  can_manage_products   boolean DEFAULT false,
  created_at            timestamp without time zone DEFAULT now(),
  phone                 text,
  loyalty_points        integer DEFAULT 0,
  permissions           jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- ---- addresses (müşteri adresleri) ----------------------------------------
CREATE TABLE IF NOT EXISTS public.addresses (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  label         text NOT NULL,
  full_address  text NOT NULL,
  notes         text,
  is_default    boolean DEFAULT false,
  created_at    timestamp with time zone DEFAULT now()
);

-- ---- ingredients (stok/reçete malzemeleri) -----------------------------------
CREATE TABLE IF NOT EXISTS public.ingredients (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              text NOT NULL,
  unit              text NOT NULL DEFAULT 'adet',
  stock_amount      numeric(10,2) NOT NULL DEFAULT 0,
  min_stock_alert   numeric(10,2) NOT NULL DEFAULT 0,
  container_name    text,
  container_size    numeric(10,2) NOT NULL DEFAULT 0,
  image_url         text,
  created_at        timestamp without time zone DEFAULT now(),
  is_synced         boolean NOT NULL DEFAULT false,
  remote_id         text,
  local_id          text UNIQUE
);

-- ---- product_ingredients (ürün <-> malzeme reçete bağlantısı) ---------------
CREATE TABLE IF NOT EXISTS public.product_ingredients (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id     bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  ingredient_id  bigint NOT NULL REFERENCES public.ingredients(id) ON DELETE CASCADE,
  amount_used    numeric(10,2) NOT NULL
);

-- ---- product_variants (ürün varyantları, örn. boy) ---------------------------
CREATE TABLE IF NOT EXISTS public.product_variants (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id     text UNIQUE,
  product_id   integer REFERENCES public.products(id) ON DELETE CASCADE,
  name         text NOT NULL,
  price        numeric(10,2) NOT NULL,
  created_at   timestamp without time zone DEFAULT now()
);

-- ---- modifiers (kategori ya da ürün bazlı ek seçenekler) --------------------
CREATE TABLE IF NOT EXISTS public.modifiers (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id     text NOT NULL UNIQUE,
  category_id  bigint REFERENCES public.categories(id) ON DELETE CASCADE,
  product_id   bigint REFERENCES public.products(id) ON DELETE CASCADE,
  name         text NOT NULL,
  price_delta  numeric(10,2) NOT NULL DEFAULT 0,
  sort_order   integer NOT NULL DEFAULT 0,
  is_active    boolean NOT NULL DEFAULT true,
  created_at   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT modifiers_scope_check CHECK (((category_id IS NULL) <> (product_id IS NULL)))
);

-- ---- product_modifier_excludes (ürüne özel hariç tutulan modifier'lar) -----
CREATE TABLE IF NOT EXISTS public.product_modifier_excludes (
  product_id   bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  modifier_id  bigint NOT NULL REFERENCES public.modifiers(id) ON DELETE CASCADE,
  created_at   timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (product_id, modifier_id)
);

-- ---- orders --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.orders (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id              text UNIQUE,
  status                text DEFAULT 'completed',
  payment_method        text,
  total                 numeric(10,2) DEFAULT 0,
  is_synced             boolean DEFAULT false,
  created_at            timestamp with time zone,
  closed_at             timestamp with time zone,
  table_id              integer REFERENCES public.tables(id) ON DELETE SET NULL,
  closed_by             uuid REFERENCES auth.users(id),
  waiter_name           text,
  order_type            text DEFAULT 'dine_in',
  customer_id           uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  delivery_address_id   integer REFERENCES public.addresses(id) ON DELETE SET NULL,
  customer_note         text,
  user_id               uuid REFERENCES auth.users(id),
  discount              numeric NOT NULL DEFAULT 0,
  CONSTRAINT orders_order_type_check CHECK ((order_type = ANY (ARRAY['dine_in'::text, 'takeaway'::text, 'delivery'::text])))
);

-- ---- order_items ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.order_items (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id     text UNIQUE,
  order_id     bigint REFERENCES public.orders(id),
  quantity     integer NOT NULL,
  unit_price   numeric(10,2) NOT NULL,
  is_synced    boolean DEFAULT false,
  product_id   integer REFERENCES public.products(id),
  variant_id   integer REFERENCES public.product_variants(id),
  note         text,
  added_at     timestamp with time zone DEFAULT now()
);

-- ---- order_item_modifiers --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.order_item_modifiers (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id       text NOT NULL UNIQUE,
  order_item_id  bigint NOT NULL REFERENCES public.order_items(id) ON DELETE CASCADE,
  modifier_id    bigint REFERENCES public.modifiers(id) ON DELETE SET NULL,
  name           text NOT NULL,
  price_delta    numeric(10,2) NOT NULL,
  quantity       integer NOT NULL DEFAULT 1,
  created_at     timestamp with time zone NOT NULL DEFAULT now()
);

-- ---- payments --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payments (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        integer NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  amount          numeric(10,2) NOT NULL,
  payment_method  text NOT NULL,
  payer_label     text,
  processed_by    uuid REFERENCES auth.users(id),
  device          text DEFAULT 'mobile',
  created_at      timestamp with time zone NOT NULL DEFAULT now(),
  local_id        text NOT NULL UNIQUE,
  is_synced       boolean DEFAULT true,
  CONSTRAINT payments_amount_check CHECK ((amount > (0)::numeric)),
  CONSTRAINT payments_payment_method_check CHECK ((payment_method = ANY (ARRAY['cash'::text, 'card'::text, 'iban'::text, 'points'::text])))
);

COMMENT ON COLUMN public.payments.payer_label IS 'Optional human label, e.g. "Müşteri 1" or "Ali".';
COMMENT ON COLUMN public.payments.device IS 'Origin of the payment event (mobile, desktop, etc.).';

-- ---- payment_items ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payment_items (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id     integer NOT NULL REFERENCES public.payments(id) ON DELETE CASCADE,
  order_item_id  bigint NOT NULL UNIQUE REFERENCES public.order_items(id) ON DELETE CASCADE
);


-- =============================================================================
-- 3. INDEX'LER (kısıtlardan otomatik oluşmayan ek index'ler)
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_addresses_profile ON public.addresses USING btree (profile_id);
CREATE INDEX IF NOT EXISTS idx_modifiers_category_id ON public.modifiers USING btree (category_id);
CREATE INDEX IF NOT EXISTS idx_modifiers_product_id ON public.modifiers USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_order_item_modifiers_item_id ON public.order_item_modifiers USING btree (order_item_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON public.orders USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status_table_id ON public.orders USING btree (status, table_id);
CREATE INDEX IF NOT EXISTS orders_user_id_idx ON public.orders USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_payment_items_payment_id ON public.payment_items USING btree (payment_id);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON public.payments USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON public.payments USING btree (order_id);

-- NOT: profiles_customer_phone_unique index'i normalize_phone() fonksiyonuna
-- bağımlı olduğu için 4. bölümde (fonksiyonlardan hemen sonra) oluşturulur.


-- =============================================================================
-- 4. FONKSİYONLAR (public şeması, 7 adet — orijinal tanımlarla birebir)
-- =============================================================================

CREATE OR REPLACE FUNCTION public.normalize_phone(p text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
  SELECT NULLIF(
    CASE
      WHEN length(d) > 10 AND left(d, 2) = '90' THEN right(d, 10)
      WHEN length(d) = 11 AND left(d, 1) = '0'  THEN right(d, 10)
      ELSE d
    END, '')
  FROM (SELECT regexp_replace(coalesce(p, ''), '[^0-9]', '', 'g') AS d) t
$function$;

-- normalize_phone() artık mevcut — telefon bazlı benzersiz index'i şimdi kurabiliriz.
CREATE UNIQUE INDEX IF NOT EXISTS profiles_customer_phone_unique
  ON public.profiles USING btree (normalize_phone(phone))
  WHERE ((role = 'customer'::text) AND (phone IS NOT NULL) AND (phone <> ''::text));

CREATE OR REPLACE FUNCTION public.is_staff()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin', 'waiter')
  );
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.profiles (id, full_name, phone, role, loyalty_points)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    public.normalize_phone(NEW.raw_user_meta_data->>'phone'),
    COALESCE(NEW.raw_user_meta_data->>'role', 'customer'),
    0
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.phone_in_use(p_phone text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM profiles
    WHERE role = 'customer'
      AND normalize_phone(phone) IS NOT NULL
      AND normalize_phone(phone) = normalize_phone(p_phone)
  );
$function$;

CREATE OR REPLACE FUNCTION public.award_loyalty_points()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  earned integer;
begin
  if new.status = 'completed'
     and (old.status is distinct from 'completed')
     and new.user_id is not null then

    select coalesce(sum(oi.quantity * p.points_value), 0)
      into earned
      from order_items oi
      join products p on p.id = oi.product_id
      where oi.order_id = new.id;

    if earned > 0 then
      update profiles
        set loyalty_points = coalesce(loyalty_points, 0) + earned
        where id = new.user_id;
    end if;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.revoke_loyalty_points()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  earned integer;
begin
  if new.status = 'cancelled'
     and old.status = 'completed'
     and new.user_id is not null then

    select coalesce(sum(oi.quantity * p.points_value), 0)
      into earned
      from order_items oi
      join products p on p.id = oi.product_id
      where oi.order_id = new.id;

    if earned > 0 then
      update profiles
        set loyalty_points = greatest(0, coalesce(loyalty_points, 0) - earned)
        where id = new.user_id;
    end if;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.redeem_loyalty_points(p_user_id uuid, p_points integer, p_expected_balance integer)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_new_balance integer;
begin
  if not is_staff() then
    raise exception 'yetkisiz: sadece personel puan kullanabilir';
  end if;
  if p_points is null or p_points <= 0 then
    raise exception 'geçersiz puan miktarı';
  end if;

  -- Optimistic lock: only deduct if the balance still equals what the
  -- cashier saw on screen — a concurrent spend elsewhere matches 0 rows.
  update profiles
     set loyalty_points = loyalty_points - p_points
   where id = p_user_id
     and loyalty_points = p_expected_balance
     and loyalty_points >= p_points
  returning loyalty_points into v_new_balance;

  if v_new_balance is null then
    raise exception 'bakiye değişti';
  end if;
  return v_new_balance;
end;
$function$;


-- =============================================================================
-- 5. TRIGGER'LAR
-- =============================================================================

DROP TRIGGER IF EXISTS trg_award_loyalty_points ON public.orders;
CREATE TRIGGER trg_award_loyalty_points
  AFTER UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.award_loyalty_points();

DROP TRIGGER IF EXISTS trg_revoke_loyalty_points ON public.orders;
CREATE TRIGGER trg_revoke_loyalty_points
  AFTER UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.revoke_loyalty_points();

-- auth.users üzerindeki trigger: yeni kullanıcı kaydolduğunda profiles satırı oluşturur.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- =============================================================================
-- 6. ROW LEVEL SECURITY + POLICY'LER
-- =============================================================================

ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.modifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_item_modifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_modifier_excludes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tables ENABLE ROW LEVEL SECURITY;

-- ---- addresses ---------------------------------------------------------------
DROP POLICY IF EXISTS addresses_delete ON public.addresses;
CREATE POLICY addresses_delete ON public.addresses FOR DELETE TO authenticated
  USING (((profile_id = auth.uid()) OR is_staff()));

DROP POLICY IF EXISTS addresses_insert ON public.addresses;
CREATE POLICY addresses_insert ON public.addresses FOR INSERT TO authenticated
  WITH CHECK (((profile_id = auth.uid()) OR is_staff()));

DROP POLICY IF EXISTS addresses_select ON public.addresses;
CREATE POLICY addresses_select ON public.addresses FOR SELECT TO authenticated
  USING (((profile_id = auth.uid()) OR is_staff()));

DROP POLICY IF EXISTS addresses_update ON public.addresses;
CREATE POLICY addresses_update ON public.addresses FOR UPDATE TO authenticated
  USING (((profile_id = auth.uid()) OR is_staff()))
  WITH CHECK (((profile_id = auth.uid()) OR is_staff()));

-- ---- categories ----------------------------------------------------------
DROP POLICY IF EXISTS categories_delete ON public.categories;
CREATE POLICY categories_delete ON public.categories FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS categories_insert ON public.categories;
CREATE POLICY categories_insert ON public.categories FOR INSERT TO authenticated
  WITH CHECK (is_staff());

DROP POLICY IF EXISTS categories_select ON public.categories;
CREATE POLICY categories_select ON public.categories FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS categories_update ON public.categories;
CREATE POLICY categories_update ON public.categories FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- ingredients ---------------------------------------------------------
DROP POLICY IF EXISTS ingredients_delete ON public.ingredients;
CREATE POLICY ingredients_delete ON public.ingredients FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS ingredients_insert ON public.ingredients;
CREATE POLICY ingredients_insert ON public.ingredients FOR INSERT TO authenticated
  WITH CHECK (is_staff());

DROP POLICY IF EXISTS ingredients_select ON public.ingredients;
CREATE POLICY ingredients_select ON public.ingredients FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS ingredients_update ON public.ingredients;
CREATE POLICY ingredients_update ON public.ingredients FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- modifiers -----------------------------------------------------------
DROP POLICY IF EXISTS modifiers_delete ON public.modifiers;
CREATE POLICY modifiers_delete ON public.modifiers FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS modifiers_insert ON public.modifiers;
CREATE POLICY modifiers_insert ON public.modifiers FOR INSERT TO authenticated
  WITH CHECK (is_staff());

DROP POLICY IF EXISTS modifiers_select ON public.modifiers;
CREATE POLICY modifiers_select ON public.modifiers FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS modifiers_update ON public.modifiers;
CREATE POLICY modifiers_update ON public.modifiers FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- order_item_modifiers --------------------------------------------------
DROP POLICY IF EXISTS oim_delete ON public.order_item_modifiers;
CREATE POLICY oim_delete ON public.order_item_modifiers FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS oim_insert ON public.order_item_modifiers;
CREATE POLICY oim_insert ON public.order_item_modifiers FOR INSERT TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS oim_select ON public.order_item_modifiers;
CREATE POLICY oim_select ON public.order_item_modifiers FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS oim_update ON public.order_item_modifiers;
CREATE POLICY oim_update ON public.order_item_modifiers FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- order_items -----------------------------------------------------------
DROP POLICY IF EXISTS order_items_delete ON public.order_items;
CREATE POLICY order_items_delete ON public.order_items FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS order_items_insert ON public.order_items;
CREATE POLICY order_items_insert ON public.order_items FOR INSERT TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS order_items_select ON public.order_items;
CREATE POLICY order_items_select ON public.order_items FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS order_items_update ON public.order_items;
CREATE POLICY order_items_update ON public.order_items FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- orders --------------------------------------------------------------
DROP POLICY IF EXISTS orders_delete ON public.orders;
CREATE POLICY orders_delete ON public.orders FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS orders_insert ON public.orders;
CREATE POLICY orders_insert ON public.orders FOR INSERT TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS orders_select ON public.orders;
CREATE POLICY orders_select ON public.orders FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS orders_update ON public.orders;
CREATE POLICY orders_update ON public.orders FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- payment_items ----------------------------------------------------------
DROP POLICY IF EXISTS payment_items_delete ON public.payment_items;
CREATE POLICY payment_items_delete ON public.payment_items FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS payment_items_insert ON public.payment_items;
CREATE POLICY payment_items_insert ON public.payment_items FOR INSERT TO authenticated
  WITH CHECK (is_staff());

DROP POLICY IF EXISTS payment_items_select ON public.payment_items;
CREATE POLICY payment_items_select ON public.payment_items FOR SELECT TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS payment_items_update ON public.payment_items;
CREATE POLICY payment_items_update ON public.payment_items FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- payments --------------------------------------------------------------
DROP POLICY IF EXISTS payments_delete ON public.payments;
CREATE POLICY payments_delete ON public.payments FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS payments_insert ON public.payments;
CREATE POLICY payments_insert ON public.payments FOR INSERT TO authenticated
  WITH CHECK (is_staff());

DROP POLICY IF EXISTS payments_select ON public.payments;
CREATE POLICY payments_select ON public.payments FOR SELECT TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS payments_update ON public.payments;
CREATE POLICY payments_update ON public.payments FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- product_ingredients ----------------------------------------------------
DROP POLICY IF EXISTS product_ingredients_delete ON public.product_ingredients;
CREATE POLICY product_ingredients_delete ON public.product_ingredients FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS product_ingredients_insert ON public.product_ingredients;
CREATE POLICY product_ingredients_insert ON public.product_ingredients FOR INSERT TO authenticated
  WITH CHECK (is_staff());

DROP POLICY IF EXISTS product_ingredients_select ON public.product_ingredients;
CREATE POLICY product_ingredients_select ON public.product_ingredients FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS product_ingredients_update ON public.product_ingredients;
CREATE POLICY product_ingredients_update ON public.product_ingredients FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- product_modifier_excludes ----------------------------------------------
DROP POLICY IF EXISTS pmod_excludes_delete ON public.product_modifier_excludes;
CREATE POLICY pmod_excludes_delete ON public.product_modifier_excludes FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS pmod_excludes_insert ON public.product_modifier_excludes;
CREATE POLICY pmod_excludes_insert ON public.product_modifier_excludes FOR INSERT TO authenticated
  WITH CHECK (is_staff());

DROP POLICY IF EXISTS pmod_excludes_select ON public.product_modifier_excludes;
CREATE POLICY pmod_excludes_select ON public.product_modifier_excludes FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS pmod_excludes_update ON public.product_modifier_excludes;
CREATE POLICY pmod_excludes_update ON public.product_modifier_excludes FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- product_variants --------------------------------------------------------
DROP POLICY IF EXISTS product_variants_delete ON public.product_variants;
CREATE POLICY product_variants_delete ON public.product_variants FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS product_variants_insert ON public.product_variants;
CREATE POLICY product_variants_insert ON public.product_variants FOR INSERT TO authenticated
  WITH CHECK (is_staff());

DROP POLICY IF EXISTS product_variants_select ON public.product_variants;
CREATE POLICY product_variants_select ON public.product_variants FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS product_variants_update ON public.product_variants;
CREATE POLICY product_variants_update ON public.product_variants FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- products --------------------------------------------------------------
DROP POLICY IF EXISTS products_delete ON public.products;
CREATE POLICY products_delete ON public.products FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS products_insert ON public.products;
CREATE POLICY products_insert ON public.products FOR INSERT TO authenticated
  WITH CHECK (is_staff());

DROP POLICY IF EXISTS products_select ON public.products;
CREATE POLICY products_select ON public.products FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS products_update ON public.products;
CREATE POLICY products_update ON public.products FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- profiles --------------------------------------------------------------
DROP POLICY IF EXISTS profiles_select ON public.profiles;
CREATE POLICY profiles_select ON public.profiles FOR SELECT TO authenticated
  USING (((id = auth.uid()) OR is_staff()));

DROP POLICY IF EXISTS profiles_update ON public.profiles;
CREATE POLICY profiles_update ON public.profiles FOR UPDATE TO authenticated
  USING ((id = auth.uid()))
  WITH CHECK ((id = auth.uid()));

-- ---- tables (masalar) ---------------------------------------------------
DROP POLICY IF EXISTS tables_delete ON public.tables;
CREATE POLICY tables_delete ON public.tables FOR DELETE TO authenticated
  USING (is_staff());

DROP POLICY IF EXISTS tables_insert ON public.tables;
CREATE POLICY tables_insert ON public.tables FOR INSERT TO authenticated
  WITH CHECK (is_staff());

DROP POLICY IF EXISTS tables_select ON public.tables;
CREATE POLICY tables_select ON public.tables FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS tables_update ON public.tables;
CREATE POLICY tables_update ON public.tables FOR UPDATE TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ---- storage.objects (product-images / category-images bucket'ları) --------
DROP POLICY IF EXISTS "Authenticated deletes images" ON storage.objects;
CREATE POLICY "Authenticated deletes images" ON storage.objects FOR DELETE TO authenticated
  USING ((bucket_id = ANY (ARRAY['product-images'::text, 'category-images'::text])));

DROP POLICY IF EXISTS "Authenticated reads images" ON storage.objects;
CREATE POLICY "Authenticated reads images" ON storage.objects FOR SELECT TO authenticated
  USING ((bucket_id = ANY (ARRAY['product-images'::text, 'category-images'::text])));

DROP POLICY IF EXISTS "Authenticated updates images" ON storage.objects;
CREATE POLICY "Authenticated updates images" ON storage.objects FOR UPDATE TO authenticated
  USING ((bucket_id = ANY (ARRAY['product-images'::text, 'category-images'::text])))
  WITH CHECK ((bucket_id = ANY (ARRAY['product-images'::text, 'category-images'::text])));

DROP POLICY IF EXISTS "Authenticated uploads images" ON storage.objects;
CREATE POLICY "Authenticated uploads images" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK ((bucket_id = ANY (ARRAY['product-images'::text, 'category-images'::text])));


-- =============================================================================
-- 7. STORAGE BUCKET'LARI
-- =============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('product-images', 'product-images', true, NULL, NULL),
  ('category-images', 'category-images', true, NULL, NULL)
ON CONFLICT (id) DO NOTHING;


-- =============================================================================
-- 8. REALTIME PUBLICATION ÜYELİĞİ
-- =============================================================================
-- Her tabloyu supabase_realtime publication'ına, zaten üye değilse ekler.

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'categories', 'ingredients', 'order_items', 'orders',
    'payment_items', 'payments', 'product_variants', 'products', 'tables'
  ]
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = t
    ) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
    END IF;
  END LOOP;
END $$;


-- =============================================================================
-- 9. FONKSİYON GRANT / REVOKE'LARI
-- =============================================================================
-- Canlı projedeki etkin izinleri birebir yeniden üretir (tighten_storage_and_
-- function_grants migration'ının sonucu). Trigger fonksiyonları ve hassas RPC'ler
-- PUBLIC'ten kısıtlanır; sadece gereken rollere EXECUTE verilir.

REVOKE ALL ON FUNCTION public.award_loyalty_points() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.award_loyalty_points() TO service_role;

REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;

REVOKE ALL ON FUNCTION public.is_staff() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_staff() TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.phone_in_use(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.phone_in_use(text) TO anon, authenticated, service_role;

REVOKE ALL ON FUNCTION public.redeem_loyalty_points(uuid, integer, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.redeem_loyalty_points(uuid, integer, integer) TO authenticated, service_role;

-- normalize_phone() ve revoke_loyalty_points() canlı projede PUBLIC'e açık
-- kalmış (CREATE FUNCTION varsayılanı) — davranışı birebir korumak için
-- burada dokunulmuyor; PUBLIC zaten EXECUTE hakkına sahip.
GRANT EXECUTE ON FUNCTION public.normalize_phone(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.revoke_loyalty_points() TO PUBLIC;


-- =============================================================================
-- 10. SEED DATA — SADECE MASALAR (tables)
-- =============================================================================
-- Ürün/sipariş gibi diğer veriler test verisidir ve KASITLI olarak dahil
-- edilmemiştir. auth.users satırı da eklenmez.

INSERT INTO public.tables (id, name, status) VALUES
  (1, 'Masa 1', 'empty'),
  (2, 'Masa 2', 'empty'),
  (3, 'Masa 3', 'empty'),
  (4, 'Masa 4', 'empty'),
  (5, 'Masa 5', 'empty'),
  (6, 'Masa 6', 'empty'),
  (7, 'Masa 7', 'empty'),
  (8, 'Masa 8', 'empty'),
  (9, 'Masa 9', 'empty'),
  (10, 'Masa 10', 'empty'),
  (11, 'Masa 11', 'empty'),
  (12, 'Masa 12', 'empty'),
  (13, 'Masa 13', 'empty'),
  (14, 'Masa 14', 'empty'),
  (15, 'Masa 15', 'empty'),
  (16, 'Masa 16', 'empty'),
  (17, 'Masa 17', 'empty'),
  (18, 'Masa 18', 'empty'),
  (19, 'Masa 19', 'empty'),
  (20, 'Masa 20', 'empty')
ON CONFLICT (id) DO NOTHING;

-- id serial/identity sütununu, eklenen en yüksek id'nin üstüne resetle.
SELECT setval(
  pg_get_serial_sequence('public.tables', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.tables), 1),
  true
);

-- =============================================================================
-- BOOTSTRAP TAMAMLANDI
-- =============================================================================
